import com.github.easai.math.Complex;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	Complex c=new Complex(0.0,1.0);
        System.out.println(Complex.sin(c).toString());
    }
}
